[package]
name = "amigo_tilemap"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
amigo_core = { workspace = true }
serde = { workspace = true }
rustc-hash = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
