//! Sprite animation from an Aseprite file.
//!
//! `assets/sprites/hero.aseprite` holds nine frames and three tags. The engine
//! loads it as the sprite `"hero"` (all frames in one strip) and registers one
//! animation per tag: `"hero/idle"` (ping-pong), `"hero/walk"` (loop) and
//! `"hero/jump"` (repeat count 1, so it plays once). Edit the file in Aseprite
//! while the demo runs and hot reload picks the change up.
//!
//! The file is generated by `scripts/gen_aseprite_fixtures.py`, so the
//! repository needs no Aseprite install to rebuild it.

use amigo_engine::prelude::*;

const SPEED: f32 = 60.0; // virtual pixels per second
const GROUND_Y: f32 = 60.0;

struct AnimationDemo {
    hero: AnimPlayer,
    x: f32,
    facing_left: bool,
}

impl AnimationDemo {
    fn new() -> Self {
        Self {
            hero: AnimPlayer::new("hero/idle"),
            x: 72.0,
            facing_left: false,
        }
    }

    /// Switch to `name` in the mode its tag defines (loop, ping-pong unrolled
    /// into the frames, or once). A no-op while it is already playing.
    fn play(&mut self, ctx: &GameContext, name: &str) {
        if let Some(animation) = ctx.assets.animation(name) {
            self.hero.play_animation(animation);
        }
    }
}

impl Game for AnimationDemo {
    fn update(&mut self, ctx: &mut GameContext) -> SceneAction {
        let jumping = self.hero.current_animation == "hero/jump" && !self.hero.finished;

        if !jumping {
            let left = ctx.input.held(KeyCode::ArrowLeft);
            let right = ctx.input.held(KeyCode::ArrowRight);
            if ctx.input.pressed(KeyCode::Space) {
                self.play(ctx, "hero/jump");
                // A finished jump is still the current animation; start over.
                self.hero.restart();
            } else if left != right {
                self.facing_left = left;
                let dir = if left { -1.0 } else { 1.0 };
                self.x = (self.x + dir * SPEED * ctx.time.dt).clamp(0.0, 144.0);
                self.play(ctx, "hero/walk");
            } else {
                self.play(ctx, "hero/idle");
            }
        }

        // One animation tick per fixed-timestep tick.
        self.hero.advance(ctx.assets.animations());
        SceneAction::Continue
    }

    fn draw(&self, ctx: &mut DrawContext) {
        ctx.draw_rect(
            Rect::new(0.0, GROUND_Y + 16.0, 160.0, 2.0),
            Color::from_rgba(90, 90, 110, 255),
        );
        // The art faces right; flip it to face left.
        let facing_left = self.facing_left;
        ctx.draw_animated_ex(
            "hero",
            &self.hero,
            RenderVec2::new(self.x, GROUND_Y),
            |sprite| sprite.flip_x = facing_left,
        );

        let state = self
            .hero
            .current_animation
            .strip_prefix("hero/")
            .unwrap_or(&self.hero.current_animation);
        ctx.draw_text(
            &format!("{state} frame {}", self.hero.frame_index + 1),
            4.0,
            4.0,
            Color::WHITE,
        );
        ctx.draw_text(
            "Arrows walk, Space jumps",
            4.0,
            14.0,
            Color::from_rgba(180, 180, 180, 255),
        );
    }
}

fn main() {
    Engine::build()
        .title("Animation Demo")
        .virtual_resolution(160, 90)
        // Found wherever the demo is started from, not only from its own
        // directory.
        .assets_path(concat!(env!("CARGO_MANIFEST_DIR"), "/assets"))
        .build()
        .run(AnimationDemo::new());
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_hero_sprite_has_the_tags_the_demo_plays() {
        let mut assets = AssetManager::new(concat!(env!("CARGO_MANIFEST_DIR"), "/assets"));
        assets.load_sprites().expect("assets load");
        let hero = assets.sprite("hero").expect("hero.aseprite loads");
        assert_eq!((hero.width, hero.height), (16 * 9, 16));
        assert!(assets.animation("hero/idle").is_some_and(|a| a.looping));
        assert!(assets.animation("hero/walk").is_some_and(|a| a.looping));
        assert!(assets.animation("hero/jump").is_some_and(|a| !a.looping));
    }
}
